name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: roblox-ts/setup-rokit@v0.1.2

      - name: Install dependencies
        run: wally install

      - name: Build .rbxm
        run: rojo build -o starknet-luau.rbxm

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: starknet-luau.rbxm
          generate_release_notes: true

      - name: Publish to Wally
        env:
          WALLY_AUTH_TOKEN: ${{ secrets.WALLY_AUTH_TOKEN }}
        run: |
          wally login --project-path . --token "$WALLY_AUTH_TOKEN"
          wally publish

      - name: Install Pesde
        uses: axiom-co/setup-pesde@v0.4.1
        with:
          token: ${{ secrets.PESDE_TOKEN }}

      - name: Publish to Pesde
        run: |
          pesde install
          pesde publish -y
